[[snippets]]
trigger = ",refcom"
replace = "$refactor-pass then commit"

[[snippets]]
trigger = ",aii"
replace = "Investigate and plan issue {{cursor}} then $ask-questions-if-underspecified"

[[snippets]]
trigger = ",ccc"
replace = "refactor pass then update/close issue(s) and commit then regroup"
