-- Generated by script/design-system. Do not edit.
-- Mekanikos Light window chrome from White Pill Studio's recipe.window. The theme's
-- hyprland.lua applies it: hl.config(require("omarchy.current.theme.hyprland_window"))
return {
	general = {
		border_size = 4,
		gaps_in = 2,
		gaps_out = { top = 4, right = 12, bottom = 12, left = 12 },
		col = {
			active_border = "rgba(1853c7ff)",
			inactive_border = "rgba(ffffff22)",
		},
	},
	decoration = {
		rounding = 14,
		rounding_power = 2,
		shadow = {
			range = 18,
			color = "rgba(10131a1f)",
			color_inactive = "rgba(10131a1f)",
			offset = { 0, 4 },
		},
	},
	group = {
		col = {
			border_active = "rgba(1853c7ff)",
			border_inactive = "rgba(ffffff22)",
		},
	},
	plugin = {
		borders_plus_plus = {
			border_size_1 = 4,
			col = {
				border_1 = "rgba(1853c7ff)",
			},
		},
	},
}
