// Generated by script/design-system. Do not edit.
.pragma library

function raw(values, key, fallback) {
  if (!values) return fallback
  var value = values[key]
  return value === undefined || value === null || String(value).length === 0 ? fallback : value
}

function number(values, key, fallback) {
  var value = Number(raw(values, key, fallback))
  return isFinite(value) ? value : fallback
}

function color(values, key, fallback) {
  return String(raw(values, key, fallback))
}

function shadow(values, section) {
  var prefix = String(section || "popups") + "."
  return {
    color: color(values, prefix + "shadow-color", "#10131A"),
    alpha: number(values, prefix + "shadow-alpha", 0.12),
    blur: number(values, prefix + "shadow-blur", 18),
    x: number(values, prefix + "shadow-x", 0),
    y: number(values, prefix + "shadow-y", 4),
  }
}

function innerBorder(values, section) {
  var prefix = String(section || "popups") + "."
  return {
    color: color(values, prefix + "inner-border", "#2C363C"),
    alpha: number(values, prefix + "inner-border-alpha", 0.14),
    width: number(values, prefix + "inner-border-width", 0.5),
  }
}

function gutterLeft(shadow) { return Math.max(0, shadow.blur - shadow.x) }
function gutterTop(shadow) { return Math.max(0, shadow.blur - shadow.y) }
function gutterRight(shadow) { return Math.max(0, shadow.blur + shadow.x) }
function gutterBottom(shadow) { return Math.max(0, shadow.blur + shadow.y) }
