#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Load colors
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=32 blur_radius=0 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=0
  icon.font="Hack Nerd Font:Regular:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=$DEFAULT_ICON_COLOR
  label.color=$DEFAULT_LABEL_COLOR
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=0
  label.padding_right=10
  background.padding_left=4
  background.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change
sketchybar --add event dinky_workspace_changing
sketchybar --add event aerospace_mode_changed
sketchybar --add event dinky_mode_changed
sketchybar --add event appearance_changed AppleInterfaceThemeChangedNotification

# Reload the palette as soon as macOS changes between light and dark mode.
sketchybar --add item appearance_observer left \
  --set appearance_observer drawing=off script="$PLUGIN_DIR/appearance.sh" \
  --subscribe appearance_observer appearance_changed

# One item per workspace, named space.<workspace>. dinky numbers workspaces across displays, so a workspace
# on the side display (AeroSpace's a1, dinky's [workspace-to-display]) is just a number that lives there;
# plugins/dinky_spaces.sh draws it as an arrow while it does. Side-display workspaces come first, as that
# display sits left of the main one. A click shows the workspace and focuses its display.
DINKY="$HOME/.local/bin/dinky"
while read -r is_main workspace; do
  [ -n "$workspace" ] || continue
  sketchybar --add item space.$workspace left \
    --set space.$workspace \
    background.color=$TRANSPARENT \
    background.corner_radius=5 \
    background.height=26 \
    background.drawing=off \
    background.padding_left=6 \
    background.padding_right=6 \
    y_offset=0 \
    icon="$workspace" \
    icon.font="SF Pro:Bold:16.0" \
    icon.highlight_color=$SPACE_HIGHLIGHT_COLOR \
    label.drawing=off \
    label.font="sketchybar-app-font:Regular:14.0" \
    label.y_offset=-1 \
    click_script="$DINKY workspace $workspace"
done <<<"$($DINKY list-workspaces --all --format '%{monitor-is-main} %{workspace}' | sort -k1,1 -s)"

# Refreshes all of the above when dinky starts and ends a switch, when focus moves, and when displays change.
sketchybar --add item dinky_spaces left \
  --set dinky_spaces drawing=off updates=on script="$CONFIG_DIR/plugins/dinky_spaces.sh" \
  --subscribe dinky_spaces dinky_workspace_changing aerospace_workspace_change aerospace_mode_changed front_app_switched display_change system_woke

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
  --set chevron icon= label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off label.drawing=on script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched \
  --add item front_app_layout left \
  --set front_app_layout \
  icon.drawing=on \
  icon.font="Hack Nerd Font:Regular:11.0" \
  icon.color=$FRONT_APP_LAYOUT_ICON_COLOR \
  icon.padding_left=6 \
  icon.padding_right=6 \
  label.drawing=off \
  background.drawing=on \
  background.color=$FRONT_APP_LAYOUT_BG_COLOR \
  background.corner_radius=4 \
  background.height=16 \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app_layout front_app_switched aerospace_mode_changed \
  --add item dinky_mode left \
  --set dinky_mode \
  drawing=off \
  icon.drawing=off \
  label.font="SF Pro:Bold:10.0" \
  label.color=$DINKY_MODE_LABEL_COLOR \
  label.padding_left=6 \
  label.padding_right=6 \
  background.drawing=on \
  background.color=$DINKY_MODE_BG_COLOR \
  background.corner_radius=4 \
  background.height=16 \
  script="$PLUGIN_DIR/dinky_mode.sh" \
  --subscribe dinky_mode dinky_mode_changed

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item battery right \
  --set battery update_freq=120 icon.drawing=on icon.font="Hack Nerd Font:Regular:14.0" script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item calendar_event right \
  --set calendar_event \
  update_freq=60 \
  script="$PLUGIN_DIR/calendar_event.sh" \
  click_script="open -a Calendar" \
  icon.font="Hack Nerd Font:Regular:14.0" \
  label.color="$CAL_EVENT_LABEL_COLOR" \
  background.drawing=on \
  background.color="$CAL_EVENT_BG_COLOR" \
  background.corner_radius=8 \
  background.height=25 \
  --add item doing right \
  --set doing \
  icon.drawing=off \
  label="Doing…" \
  label.font="SF Pro:Medium:12.0" \
  label.color="$DOING_LABEL_COLOR" \
  label.padding_left=8 \
  label.padding_right=8 \
  background.drawing=on \
  background.color="$DOING_BG_COLOR" \
  background.corner_radius=4 \
  background.height=20 \
  update_freq=30 \
  script="$PLUGIN_DIR/doing.sh" \
  click_script="$PLUGIN_DIR/doing.sh edit" \
  --subscribe doing system_woke \
  --add item fut_waiting right \
  --set fut_waiting \
  drawing=on \
  width=0 \
  update_freq=5 \
  icon="●" \
  icon.drawing=off \
  icon.font="SF Pro:Bold:10.0" \
  icon.padding_left=8 \
  icon.padding_right=4 \
  label.drawing=off \
  label.font="SF Pro:Semibold:13.0" \
  label.padding_right=8 \
  script="$PLUGIN_DIR/fut_agents.sh"

# --add item things_todo right \
# --set things_todo update_freq=60 \
# script="$PLUGIN_DIR/things_todo.sh" \
# click_script="open -a Things3" \
# background.drawing=on \
# background.color=$ITEM_BG_COLOR \
# background.corner_radius=8 \
# background.height=25

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
