[controls]
normal-color = "#B4BDC3"
normal-fill-alpha = 0.04
normal-border = "#B4BDC3"
normal-border-width = 1
normal-border-alpha = 0.40
hover-cursor-color = "#1853C7"
hover-cursor-fill-alpha = 0.1
hover-cursor-border = "#1853C7"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.45
focus-color = "#1853C7"
focus-fill-alpha = 0.10
focus-border = "#1853C7"
focus-border-width = 1
focus-border-alpha = 1.0
selected-color = "#1853C7"
selected-fill-alpha = 0.22
selected-border = "#1853C7"
selected-border-width = 0
selected-border-alpha = 1.0
pressed-fill-alpha = 0.24
selection-fill-alpha = 0.28
