[font]
base-size = 14
caption = 12
body = 14
title = 16
ui-family = "Iosevka Aile"
ui-strong-family = "Iosevka Aile"
bar-family = "Iosevka Aile"
icon-family = "Iosevka Curly"
title-weight = 600
title-tracking = -0.01
subtitle-weight = 500
