extensions = [
  "/Users/mikker/dev/fut/examples/extensions/wt",
  "/Users/mikker/dev/fut/examples/extensions/run",
]

[projects.tuna]
path = "~/dev/Tuna"

[projects.dotfiles]
path = "~/.dotfiles"

[ui.bindings]
open_left_sidebar = "]"
open_right_sidebar = "w"
"wt:new-worktree" = "N"
"run:restart" = "r"

[ui.styles.current]
foreground = "#FFFFFF"
background = "#0053B5"

add_modifiers = []

[ui.tab_bar]
position = "bottom"
right = [
  { segments = [
    { token = "workspace.name", prefix = " ", suffix = " ", max_width = 20 },
  ], style = "muted", priority = 200 },
  { segments = [
    { token = "client.zoom", suffix = " " },
  ], priority = 255 },
  { segments = [
    { token = "client.help" },
  ], style = "muted", priority = 0 },
  { segments = [
    { token = "workspace.extension.run.pause", style = "divider", inverted = true, pill = true },
    { token = "workspace.extension.run.launching", style = "attention", inverted = true, pill = true },
    { token = "workspace.extension.run.play", style = "added", inverted = true, pill = true },
    { token = "workspace.extension.run.stop", style = "divider", inverted = true, pill = true },
    { token = "workspace.extension.run.cross", style = "error", inverted = true, pill = true },
  ], priority = 255 },
  # { segments = [
  #   { token = "fut" },
  # ], style = "muted", priority = 0 },
  { segments = [
    { token = "session.waiting", prefix = " ", suffix = " " },
  ], style = "attention", priority = 255 },
]

[ui.sidebar.left]
visibility = "hidden"
components = []

[ui.sidebar.right]
visibility = "automatic"
components = [
  { component = "workspaces", size = "fill", row = { right = [
    { token = "workspace.extension.run.status", prefix = " " },
    { token = "workspace.activity", prefix = " " },
    { token = "workspace.closing", prefix = " " },
    { text = " " },
  ] } },
  # { component = "agents", size = 8, scope = "session" },
]

[ui.icons]
preset = "nerd_font"

[trusted_commands.git_diff]
title = "Repository diff"
binding = "g"
program = "/Users/mikker/.dotfiles/tmux/tmux.symlink/git_diff_popup.sh"
